apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-boutique
  namespace: monitoring
spec:
  version: 8.1.2
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false